sudo: required

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project dbartalos-tiny-hawking 
  - gcloud config set compute/zone us-west2-a
  - gcloud container clusters get-credentials standard-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t dbartalos/react-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
  - docker run -e CI=true dbartalos/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./complex/deploy.sh
  on:
    branch: master