sudo: required
services:
  - docker

before_install:
  - docker build -t dbartalos/react-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
  - docker run -e CI=true dbartalos/react-test npm test -- --coverage

after_success:
  - docker build -t dbartalos/multi-client ./complex/client
  - docker build -t dbartalos/multi-nginx ./complex/nginx
  - docker build -t dbartalos/multi-server ./complex/server
  - docker build -t dbartalos/multi-worker ./complex/worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dbartalos/multi-client
  - docker push dbartalos/multi-nginx
  - docker push dbartalos/multi-server
  - docker push dbartalos/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
